//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DavidLing_Test2Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DavidLing.Test2), typeof(System.Object));
		L.RegFunction("Speak", Speak);
		L.RegFunction("New", _CreateDavidLing_Test2);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDavidLing_Test2(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DavidLing.Test2 obj = new DavidLing.Test2();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DavidLing.Test2.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Speak(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DavidLing.Test2 obj = (DavidLing.Test2)ToLua.CheckObject<DavidLing.Test2>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Speak(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

