//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Lesson3Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Lesson3), typeof(System.Object));
		L.RegFunction("New", _CreateLesson3);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("array", get_array, set_array);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLesson3(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Lesson3 obj = new Lesson3();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Lesson3.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_array(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Lesson3 obj = (Lesson3)o;
			int[] ret = obj.array;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index array on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_array(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			Lesson3 obj = (Lesson3)o;
			int[] arg0 = ToLua.CheckNumberArray<int>(L, 2);
			obj.array = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index array on a nil value");
		}
	}
}

