// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf C++ Version: 7.34.1

#include "test.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GamePlayerTest {

inline constexpr TestMsg2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        testint32_{0} {}

template <typename>
constexpr TestMsg2::TestMsg2(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TestMsg2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct TestMsg2DefaultTypeInternal {
  constexpr TestMsg2DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsg2DefaultTypeInternal() {}
  union {
    TestMsg2 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsg2DefaultTypeInternal _TestMsg2_default_instance_;

inline constexpr TestMsg_TestMsg3::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        testint32_{0} {}

template <typename>
constexpr TestMsg_TestMsg3::TestMsg_TestMsg3(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TestMsg_TestMsg3_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct TestMsg_TestMsg3DefaultTypeInternal {
  constexpr TestMsg_TestMsg3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsg_TestMsg3DefaultTypeInternal() {}
  union {
    TestMsg_TestMsg3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsg_TestMsg3DefaultTypeInternal _TestMsg_TestMsg3_default_instance_;
template <typename>
constexpr TestMsg_TestMapEntry_DoNotUse::TestMsg_TestMapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : TestMsg_TestMapEntry_DoNotUse::MapEntry(TestMsg_TestMapEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : TestMsg_TestMapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal {
  constexpr TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TestMsg_TestMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal _TestMsg_TestMapEntry_DoNotUse_default_instance_;

inline constexpr TestMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        listint_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.listint_)>()
        }
        #else
        listint_ {}
        #endif
        ,
        _listint_cached_byte_size_{0},
        teststr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        testbytes_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        testmsg2_{nullptr},
        testmsg3_{nullptr},
        testheart_{nullptr},
        testd_{0},
        testint64_{::int64_t{0}},
        testint32_{0},
        testsint32_{0},
        testsint64_{::int64_t{0}},
        testulong_{::uint64_t{0u}},
        testuint_{0u},
        testfixed32_{0u},
        testfixed64_{::uint64_t{0u}},
        testsfixed64_{::int64_t{0}},
        testsfixed32_{0},
        testenum_{static_cast< ::GamePlayerTest::TestEnum >(0)},
        testbool_{false},
        testbool2123123_{false},
        testenum2_{static_cast< ::GamePlayerTest::TestMsg_TestEnum2 >(0)},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_MAP_FIELD
        testmap_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmap_)>()
        }
        #else
        testmap_ {}
        #endif
     {}

template <typename>
constexpr TestMsg::TestMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(TestMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct TestMsgDefaultTypeInternal {
  constexpr TestMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsgDefaultTypeInternal() {}
  union {
    TestMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsgDefaultTypeInternal _TestMsg_default_instance_;
}  // namespace GamePlayerTest
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_test_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_test_2eproto = nullptr;
const ::uint32_t
    TableStruct_test_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg_TestMapEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg_TestMapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg_TestMapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg_TestMsg3, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg_TestMsg3, _impl_.testint32_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_._has_bits_),
        25, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testd_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testint32_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testint64_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testsint32_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testsint64_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testuint_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testulong_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testfixed32_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testfixed64_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testsfixed32_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testsfixed64_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testbool_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.teststr_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testbytes_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.listint_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmap_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testenum_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmsg2_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmsg3_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testenum2_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testbool2123123_),
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testheart_),
        6,
        8,
        7,
        9,
        10,
        12,
        11,
        13,
        14,
        16,
        15,
        18,
        1,
        2,
        0,
        21,
        17,
        3,
        4,
        20,
        19,
        5,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg2, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg2, _impl_.testint32_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::GamePlayerTest::TestMsg_TestMapEntry_DoNotUse)},
        {7, sizeof(::GamePlayerTest::TestMsg_TestMsg3)},
        {12, sizeof(::GamePlayerTest::TestMsg)},
        {59, sizeof(::GamePlayerTest::TestMsg2)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::GamePlayerTest::_TestMsg_TestMapEntry_DoNotUse_default_instance_._instance,
    &::GamePlayerTest::_TestMsg_TestMsg3_default_instance_._instance,
    &::GamePlayerTest::_TestMsg_default_instance_._instance,
    &::GamePlayerTest::_TestMsg2_default_instance_._instance,
};
const char descriptor_table_protodef_test_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ntest.proto\022\016GamePlayerTest\032\013test2.prot"
    "o\"\376\005\n\007TestMsg\022\022\n\005testD\030\002 \001(\001H\000\210\001\001\022\021\n\ttes"
    "tInt32\030\003 \001(\005\022\021\n\ttestInt64\030\004 \001(\003\022\022\n\ntestS"
    "Int32\030\005 \001(\021\022\022\n\ntestSInt64\030\006 \001(\022\022\020\n\010testU"
    "Int\030\007 \001(\r\022\021\n\ttestULong\030\010 \001(\004\022\023\n\013testFixe"
    "d32\030\t \001(\007\022\023\n\013testFixed64\030\n \001(\006\022\024\n\014testSF"
    "ixed32\030\013 \001(\017\022\024\n\014testSFixed64\030\014 \001(\020\022\020\n\010te"
    "stBool\030\r \001(\010\022\017\n\007testStr\030\016 \001(\t\022\021\n\ttestByt"
    "es\030\017 \001(\014\022\017\n\007listInt\030\020 \003(\005\0225\n\007testMap\030\021 \003"
    "(\0132$.GamePlayerTest.TestMsg.TestMapEntry"
    "\022*\n\010testEnum\030\022 \001(\0162\030.GamePlayerTest.Test"
    "Enum\022*\n\010testMsg2\030\023 \001(\0132\030.GamePlayerTest."
    "TestMsg2\0222\n\010testMsg3\030\024 \001(\0132 .GamePlayerT"
    "est.TestMsg.TestMsg3\0224\n\ttestEnum2\030\025 \001(\0162"
    "!.GamePlayerTest.TestMsg.TestEnum2\022\027\n\017te"
    "stBool2123123\030\027 \001(\010\022+\n\ttestHeart\030\030 \001(\0132\030"
    ".GameSystemTest.HeartMsg\032.\n\014TestMapEntry"
    "\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001\032\035\n\010Test"
    "Msg3\022\021\n\ttestInt32\030\001 \001(\005\"!\n\tTestEnum2\022\n\n\006"
    "NORMAL\020\000\022\010\n\004BOSS\020\001B\010\n\006_testDJ\004\010\026\020\027R\016test"
    "Int3233333\"\035\n\010TestMsg2\022\021\n\ttestInt32\030\001 \001("
    "\005* \n\010TestEnum\022\n\n\006NORMAL\020\000\022\010\n\004BOSS\020\005b\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_test_2eproto_deps[1] = {
        &::descriptor_table_test2_2eproto,
};
static ::absl::once_flag descriptor_table_test_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_test_2eproto = {
    false,
    false,
    883,
    descriptor_table_protodef_test_2eproto,
    "test.proto",
    &descriptor_table_test_2eproto_once,
    descriptor_table_test_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_test_2eproto::offsets,
    file_level_enum_descriptors_test_2eproto,
    file_level_service_descriptors_test_2eproto,
};
namespace GamePlayerTest {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
TestMsg_TestEnum2_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_test_2eproto);
  return file_level_enum_descriptors_test_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t TestMsg_TestEnum2_internal_data_[] = {
    131072u, 0u, };
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
TestEnum_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_test_2eproto);
  return file_level_enum_descriptors_test_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t TestEnum_internal_data_[] = {
    65536u, 32u, 16u, };
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
TestMsg_TestMapEntry_DoNotUse::TestMsg_TestMapEntry_DoNotUse()
    : SuperType(TestMsg_TestMapEntry_DoNotUse_class_data_.base()) {}
TestMsg_TestMapEntry_DoNotUse::TestMsg_TestMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, TestMsg_TestMapEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
TestMsg_TestMapEntry_DoNotUse::TestMsg_TestMapEntry_DoNotUse() : SuperType() {}
TestMsg_TestMapEntry_DoNotUse::TestMsg_TestMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL TestMsg_TestMapEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TestMsg_TestMapEntry_DoNotUse(arena);
}
constexpr auto TestMsg_TestMapEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestMsg_TestMapEntry_DoNotUse),
                                            alignof(TestMsg_TestMapEntry_DoNotUse));
}
constexpr auto TestMsg_TestMapEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TestMsg_TestMapEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &TestMsg_TestMapEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TestMsg_TestMapEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TestMsg_TestMapEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&TestMsg_TestMapEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &TestMsg_TestMapEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_test_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TestMsg_TestMapEntry_DoNotUse_class_data_ =
        TestMsg_TestMapEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TestMsg_TestMapEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TestMsg_TestMapEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TestMsg_TestMapEntry_DoNotUse_class_data_.tc_table);
  return TestMsg_TestMapEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2>
TestMsg_TestMapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TestMsg_TestMapEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg_TestMapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg_TestMapEntry_DoNotUse, _impl_.key_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string value = 2;
    {PROTOBUF_FIELD_OFFSET(TestMsg_TestMapEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\43\0\5\0\0\0\0\0"
    "GamePlayerTest.TestMsg.TestMapEntry"
    "value"
  }},
};
// ===================================================================

class TestMsg_TestMsg3::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TestMsg_TestMsg3>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestMsg_TestMsg3, _impl_._has_bits_);
};

TestMsg_TestMsg3::TestMsg_TestMsg3(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg_TestMsg3_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GamePlayerTest.TestMsg.TestMsg3)
}
TestMsg_TestMsg3::TestMsg_TestMsg3(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsg_TestMsg3& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg_TestMsg3_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TestMsg_TestMsg3::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TestMsg_TestMsg3::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.testint32_ = {};
}
TestMsg_TestMsg3::~TestMsg_TestMsg3() {
  // @@protoc_insertion_point(destructor:GamePlayerTest.TestMsg.TestMsg3)
  SharedDtor(*this);
}
inline void TestMsg_TestMsg3::SharedDtor(MessageLite& self) {
  TestMsg_TestMsg3& this_ = static_cast<TestMsg_TestMsg3&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TestMsg_TestMsg3::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TestMsg_TestMsg3(arena);
}
constexpr auto TestMsg_TestMsg3::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TestMsg_TestMsg3),
                                            alignof(TestMsg_TestMsg3));
}
constexpr auto TestMsg_TestMsg3::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TestMsg_TestMsg3_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &TestMsg_TestMsg3::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TestMsg_TestMsg3>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TestMsg_TestMsg3::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TestMsg_TestMsg3>(), &TestMsg_TestMsg3::ByteSizeLong,
              &TestMsg_TestMsg3::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TestMsg_TestMsg3, _impl_._cached_size_),
          false,
      },
      &TestMsg_TestMsg3::kDescriptorMethods,
      &descriptor_table_test_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TestMsg_TestMsg3_class_data_ =
        TestMsg_TestMsg3::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TestMsg_TestMsg3::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TestMsg_TestMsg3_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TestMsg_TestMsg3_class_data_.tc_table);
  return TestMsg_TestMsg3_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
TestMsg_TestMsg3::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestMsg_TestMsg3, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TestMsg_TestMsg3_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg_TestMsg3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 testInt32 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg_TestMsg3, _impl_.testint32_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg_TestMsg3, _impl_.testint32_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 testInt32 = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsg_TestMsg3, _impl_.testint32_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TestMsg_TestMsg3::Clear() {
// @@protoc_insertion_point(message_clear_start:GamePlayerTest.TestMsg.TestMsg3)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.testint32_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TestMsg_TestMsg3::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TestMsg_TestMsg3& this_ = static_cast<const TestMsg_TestMsg3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TestMsg_TestMsg3::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TestMsg_TestMsg3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GamePlayerTest.TestMsg.TestMsg3)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 testInt32 = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_testint32() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_testint32(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GamePlayerTest.TestMsg.TestMsg3)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TestMsg_TestMsg3::ByteSizeLong(const MessageLite& base) {
  const TestMsg_TestMsg3& this_ = static_cast<const TestMsg_TestMsg3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TestMsg_TestMsg3::ByteSizeLong() const {
  const TestMsg_TestMsg3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GamePlayerTest.TestMsg.TestMsg3)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 testInt32 = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_testint32() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_testint32());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TestMsg_TestMsg3::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TestMsg_TestMsg3*>(&to_msg);
  auto& from = static_cast<const TestMsg_TestMsg3&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GamePlayerTest.TestMsg.TestMsg3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_testint32() != 0) {
      _this->_impl_.testint32_ = from._impl_.testint32_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TestMsg_TestMsg3::CopyFrom(const TestMsg_TestMsg3& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GamePlayerTest.TestMsg.TestMsg3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsg_TestMsg3::InternalSwap(TestMsg_TestMsg3* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.testint32_, other->_impl_.testint32_);
}

::google::protobuf::Metadata TestMsg_TestMsg3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TestMsg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TestMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestMsg, _impl_._has_bits_);
};

void TestMsg::clear_testheart() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testheart_ != nullptr) _impl_.testheart_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
TestMsg::TestMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GamePlayerTest.TestMsg)
}
PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::GamePlayerTest::TestMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        listint_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.listint_)>()
        , from.listint_}
        #else
        listint_ { visibility, arena, from.listint_ }
        #endif
        ,
        _listint_cached_byte_size_{0},
        teststr_(arena, from.teststr_),
        testbytes_(arena, from.testbytes_),
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_MAP_FIELD
        testmap_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmap_)>()
        , from.testmap_}
        #else
        testmap_ { visibility, arena, from.testmap_ }
        #endif
     {}

TestMsg::TestMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const TestMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.testmsg2_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testmsg2_)
                : nullptr;
  _impl_.testmsg3_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testmsg3_)
                : nullptr;
  _impl_.testheart_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testheart_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, testd_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, testd_),
           offsetof(Impl_, testenum2_) -
               offsetof(Impl_, testd_) +
               sizeof(Impl_::testenum2_));

  // @@protoc_insertion_point(copy_constructor:GamePlayerTest.TestMsg)
}
PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        listint_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.listint_)>()
        }
        #else
        listint_ { visibility, arena }
        #endif
        ,
        _listint_cached_byte_size_{0},
        teststr_(arena),
        testbytes_(arena),
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_MAP_FIELD
        testmap_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::GamePlayerTest::TestMsg,
            PROTOBUF_FIELD_OFFSET(::GamePlayerTest::TestMsg, _impl_.testmap_)>()
        }
        #else
        testmap_ { visibility, arena }
        #endif
     {}

inline void TestMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, testmsg2_),
           0,
           offsetof(Impl_, testenum2_) -
               offsetof(Impl_, testmsg2_) +
               sizeof(Impl_::testenum2_));
}
TestMsg::~TestMsg() {
  // @@protoc_insertion_point(destructor:GamePlayerTest.TestMsg)
  SharedDtor(*this);
}
inline void TestMsg::SharedDtor(MessageLite& self) {
  TestMsg& this_ = static_cast<TestMsg&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.teststr_.Destroy();
  this_._impl_.testbytes_.Destroy();
  delete this_._impl_.testmsg2_;
  delete this_._impl_.testmsg3_;
  delete this_._impl_.testheart_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TestMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TestMsg(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto TestMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestMsg),
                                            alignof(TestMsg));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto TestMsg::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.listint_) +
          decltype(TestMsg::_impl_.listint_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmap_) +
          decltype(TestMsg::_impl_.testmap_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TestMsg), alignof(TestMsg), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TestMsg::PlacementNew_,
                                 sizeof(TestMsg),
                                 alignof(TestMsg));
  }
}
#endif
constexpr auto TestMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TestMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &TestMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TestMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TestMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TestMsg>(), &TestMsg::ByteSizeLong,
              &TestMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TestMsg, _impl_._cached_size_),
          false,
      },
      &TestMsg::kDescriptorMethods,
      &descriptor_table_test_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TestMsg_class_data_ =
        TestMsg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TestMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TestMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TestMsg_class_data_.tc_table);
  return TestMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 22, 4, 61, 2>
TestMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestMsg, _impl_._has_bits_),
    0, // no _extensions_
    24, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4280287233,  // skipmap
    offsetof(decltype(_table_), field_entries),
    22,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    TestMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional double testD = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 6, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testd_)}},
    // int32 testInt32 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.testint32_), 8>(),
     {24, 8, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testint32_)}},
    // int64 testInt64 = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TestMsg, _impl_.testint64_), 7>(),
     {32, 7, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testint64_)}},
    // sint32 testSInt32 = 5;
    {::_pbi::TcParser::FastZ32S1,
     {40, 9, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsint32_)}},
    // sint64 testSInt64 = 6;
    {::_pbi::TcParser::FastZ64S1,
     {48, 10, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsint64_)}},
    // uint32 testUInt = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.testuint_), 12>(),
     {56, 12, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testuint_)}},
    // uint64 testULong = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TestMsg, _impl_.testulong_), 11>(),
     {64, 11, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testulong_)}},
    // fixed32 testFixed32 = 9;
    {::_pbi::TcParser::FastF32S1,
     {77, 13, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testfixed32_)}},
    // fixed64 testFixed64 = 10;
    {::_pbi::TcParser::FastF64S1,
     {81, 14, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testfixed64_)}},
    // sfixed32 testSFixed32 = 11;
    {::_pbi::TcParser::FastF32S1,
     {93, 16, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsfixed32_)}},
    // sfixed64 testSFixed64 = 12;
    {::_pbi::TcParser::FastF64S1,
     {97, 15, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsfixed64_)}},
    // bool testBool = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TestMsg, _impl_.testbool_), 18>(),
     {104, 18, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbool_)}},
    // string testStr = 14;
    {::_pbi::TcParser::FastUS1,
     {114, 1, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.teststr_)}},
    // bytes testBytes = 15;
    {::_pbi::TcParser::FastBS1,
     {122, 2, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbytes_)}},
    // repeated int32 listInt = 16;
    {::_pbi::TcParser::FastV32P2,
     {386, 0, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.listint_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // .GamePlayerTest.TestEnum testEnum = 18;
    {::_pbi::TcParser::FastV32S2,
     {400, 17, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testenum_)}},
    // .GamePlayerTest.TestMsg2 testMsg2 = 19;
    {::_pbi::TcParser::FastMtS2,
     {410, 3, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmsg2_)}},
    // .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
    {::_pbi::TcParser::FastMtS2,
     {418, 4, 1,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmsg3_)}},
    // .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
    {::_pbi::TcParser::FastV32S2,
     {424, 20, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testenum2_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bool testBool2123123 = 23;
    {::_pbi::TcParser::FastV8S2,
     {440, 19, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbool2123123_)}},
    // .GameSystemTest.HeartMsg testHeart = 24;
    {::_pbi::TcParser::FastMtS2,
     {450, 5, 2,
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testheart_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional double testD = 2;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testd_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // int32 testInt32 = 3;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testint32_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int64 testInt64 = 4;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testint64_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // sint32 testSInt32 = 5;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsint32_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
    // sint64 testSInt64 = 6;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsint64_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt64)},
    // uint32 testUInt = 7;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testuint_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint64 testULong = 8;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testulong_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // fixed32 testFixed32 = 9;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testfixed32_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kFixed32)},
    // fixed64 testFixed64 = 10;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testfixed64_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kFixed64)},
    // sfixed32 testSFixed32 = 11;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsfixed32_), _Internal::kHasBitsOffset + 16, 0, (0 | ::_fl::kFcOptional | ::_fl::kSFixed32)},
    // sfixed64 testSFixed64 = 12;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testsfixed64_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kSFixed64)},
    // bool testBool = 13;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbool_), _Internal::kHasBitsOffset + 18, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string testStr = 14;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.teststr_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes testBytes = 15;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbytes_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated int32 listInt = 16;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.listint_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // map<int32, string> testMap = 17;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmap_), _Internal::kHasBitsOffset + 21, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // .GamePlayerTest.TestEnum testEnum = 18;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testenum_), _Internal::kHasBitsOffset + 17, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .GamePlayerTest.TestMsg2 testMsg2 = 19;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmsg2_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmsg3_), _Internal::kHasBitsOffset + 4, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testenum2_), _Internal::kHasBitsOffset + 20, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool testBool2123123 = 23;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testbool2123123_), _Internal::kHasBitsOffset + 19, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // .GameSystemTest.HeartMsg testHeart = 24;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testheart_), _Internal::kHasBitsOffset + 5, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg2>()},
      {::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg_TestMsg3>()},
      {::_pbi::TcParser::GetTable<::GameSystemTest::HeartMsg>()},
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 5, 9, 0)},
  }},
  {{
    "\26\0\0\0\0\0\0\0\0\0\0\0\0\7\0\0\7\0\0\0\0\0\0\0"
    "GamePlayerTest.TestMsg"
    "testStr"
    "testMap"
  }},
};
PROTOBUF_NOINLINE void TestMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:GamePlayerTest.TestMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.listint_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.teststr_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.testbytes_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.testmsg2_ != nullptr);
      _impl_.testmsg2_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.testmsg3_ != nullptr);
      _impl_.testmsg3_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.testheart_ != nullptr);
      _impl_.testheart_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000c0U)) {
    ::memset(&_impl_.testd_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.testint64_) -
        reinterpret_cast<char*>(&_impl_.testd_)) + sizeof(_impl_.testint64_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    ::memset(&_impl_.testint32_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.testsfixed64_) -
        reinterpret_cast<char*>(&_impl_.testint32_)) + sizeof(_impl_.testsfixed64_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x003f0000U)) {
    ::memset(&_impl_.testsfixed32_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.testenum2_) -
        reinterpret_cast<char*>(&_impl_.testsfixed32_)) + sizeof(_impl_.testenum2_));
    if (CheckHasBitForRepeated(cached_has_bits, 0x00200000U)) {
      _impl_.testmap_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TestMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TestMsg& this_ = static_cast<const TestMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TestMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TestMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GamePlayerTest.TestMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional double testD = 2;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this_._internal_testd(), target);
  }

  // int32 testInt32 = 3;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_testint32() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_testint32(), target);
    }
  }

  // int64 testInt64 = 4;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_testint64() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_testint64(), target);
    }
  }

  // sint32 testSInt32 = 5;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_testsint32() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
          5, this_._internal_testsint32(), target);
    }
  }

  // sint64 testSInt64 = 6;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_testsint64() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteSInt64ToArray(
          6, this_._internal_testsint64(), target);
    }
  }

  // uint32 testUInt = 7;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (this_._internal_testuint() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_testuint(), target);
    }
  }

  // uint64 testULong = 8;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (this_._internal_testulong() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          8, this_._internal_testulong(), target);
    }
  }

  // fixed32 testFixed32 = 9;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (this_._internal_testfixed32() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
          9, this_._internal_testfixed32(), target);
    }
  }

  // fixed64 testFixed64 = 10;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    if (this_._internal_testfixed64() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFixed64ToArray(
          10, this_._internal_testfixed64(), target);
    }
  }

  // sfixed32 testSFixed32 = 11;
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    if (this_._internal_testsfixed32() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteSFixed32ToArray(
          11, this_._internal_testsfixed32(), target);
    }
  }

  // sfixed64 testSFixed64 = 12;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    if (this_._internal_testsfixed64() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteSFixed64ToArray(
          12, this_._internal_testsfixed64(), target);
    }
  }

  // bool testBool = 13;
  if (CheckHasBit(cached_has_bits, 0x00040000U)) {
    if (this_._internal_testbool() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          13, this_._internal_testbool(), target);
    }
  }

  // string testStr = 14;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_teststr().empty()) {
      const ::std::string& _s = this_._internal_teststr();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GamePlayerTest.TestMsg.testStr");
      target = stream->WriteStringMaybeAliased(14, _s, target);
    }
  }

  // bytes testBytes = 15;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_testbytes().empty()) {
      const ::std::string& _s = this_._internal_testbytes();
      target = stream->WriteBytesMaybeAliased(15, _s, target);
    }
  }

  // repeated int32 listInt = 16;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._listint_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteInt32Packed(
            16, this_._internal_listint(), byte_size, target);
      }
    }
  }

  // map<int32, string> testMap = 17;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00200000U)) {
    if (!this_._internal_testmap().empty()) {
      using MapType = ::google::protobuf::Map<::int32_t, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::std::string,
                                     _pbi::WireFormatLite::TYPE_INT32,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_testmap();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              17, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GamePlayerTest.TestMsg.testMap");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              17, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GamePlayerTest.TestMsg.testMap");
        }
      }
    }
  }

  // .GamePlayerTest.TestEnum testEnum = 18;
  if (CheckHasBit(cached_has_bits, 0x00020000U)) {
    if (this_._internal_testenum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          18, this_._internal_testenum(), target);
    }
  }

  // .GamePlayerTest.TestMsg2 testMsg2 = 19;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        19, *this_._impl_.testmsg2_, this_._impl_.testmsg2_->GetCachedSize(), target,
        stream);
  }

  // .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        20, *this_._impl_.testmsg3_, this_._impl_.testmsg3_->GetCachedSize(), target,
        stream);
  }

  // .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
  if (CheckHasBit(cached_has_bits, 0x00100000U)) {
    if (this_._internal_testenum2() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          21, this_._internal_testenum2(), target);
    }
  }

  // bool testBool2123123 = 23;
  if (CheckHasBit(cached_has_bits, 0x00080000U)) {
    if (this_._internal_testbool2123123() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          23, this_._internal_testbool2123123(), target);
    }
  }

  // .GameSystemTest.HeartMsg testHeart = 24;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        24, *this_._impl_.testheart_, this_._impl_.testheart_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GamePlayerTest.TestMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TestMsg::ByteSizeLong(const MessageLite& base) {
  const TestMsg& this_ = static_cast<const TestMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TestMsg::ByteSizeLong() const {
  const TestMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GamePlayerTest.TestMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000040U & cached_has_bits) * 9;
  if (BatchCheckHasBit(cached_has_bits, 0x000000bfU)) {
    // repeated int32 listInt = 16;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_listint(), 2,
              this_._impl_._listint_cached_byte_size_);
    }
    // string testStr = 14;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_teststr().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_teststr());
      }
    }
    // bytes testBytes = 15;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_testbytes().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_testbytes());
      }
    }
    // .GamePlayerTest.TestMsg2 testMsg2 = 19;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.testmsg2_);
    }
    // .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.testmsg3_);
    }
    // .GameSystemTest.HeartMsg testHeart = 24;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.testheart_);
    }
    // int64 testInt64 = 4;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_testint64() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_testint64());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    // int32 testInt32 = 3;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_testint32() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_testint32());
      }
    }
    // sint32 testSInt32 = 5;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_testsint32() != 0) {
        total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
            this_._internal_testsint32());
      }
    }
    // sint64 testSInt64 = 6;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_testsint64() != 0) {
        total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(
            this_._internal_testsint64());
      }
    }
    // uint64 testULong = 8;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (this_._internal_testulong() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_testulong());
      }
    }
    // uint32 testUInt = 7;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (this_._internal_testuint() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_testuint());
      }
    }
    // fixed32 testFixed32 = 9;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (this_._internal_testfixed32() != 0) {
        total_size += 5;
      }
    }
    // fixed64 testFixed64 = 10;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (this_._internal_testfixed64() != 0) {
        total_size += 9;
      }
    }
    // sfixed64 testSFixed64 = 12;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (this_._internal_testsfixed64() != 0) {
        total_size += 9;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x003f0000U)) {
    // sfixed32 testSFixed32 = 11;
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      if (this_._internal_testsfixed32() != 0) {
        total_size += 5;
      }
    }
    // .GamePlayerTest.TestEnum testEnum = 18;
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      if (this_._internal_testenum() != 0) {
        total_size += 2 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_testenum());
      }
    }
    // bool testBool = 13;
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      if (this_._internal_testbool() != 0) {
        total_size += 2;
      }
    }
    // bool testBool2123123 = 23;
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      if (this_._internal_testbool2123123() != 0) {
        total_size += 3;
      }
    }
    // .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
    if (CheckHasBit(cached_has_bits, 0x00100000U)) {
      if (this_._internal_testenum2() != 0) {
        total_size += 2 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_testenum2());
      }
    }
    // map<int32, string> testMap = 17;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00200000U)) {
      total_size +=
          2 * ::google::protobuf::internal::FromIntSize(this_._internal_testmap_size());
      for (const auto& entry : this_._internal_testmap()) {
        total_size += _pbi::MapEntryFuncs<::int32_t, ::std::string,
                                       _pbi::WireFormatLite::TYPE_INT32,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TestMsg::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TestMsg*>(&to_msg);
  auto& from = static_cast<const TestMsg&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:GamePlayerTest.TestMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_listint()->MergeFrom(from._internal_listint());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_teststr().empty()) {
        _this->_internal_set_teststr(from._internal_teststr());
      } else {
        if (_this->_impl_.teststr_.IsDefault()) {
          _this->_internal_set_teststr("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_testbytes().empty()) {
        _this->_internal_set_testbytes(from._internal_testbytes());
      } else {
        if (_this->_impl_.testbytes_.IsDefault()) {
          _this->_internal_set_testbytes("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.testmsg2_ != nullptr);
      if (_this->_impl_.testmsg2_ == nullptr) {
        _this->_impl_.testmsg2_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testmsg2_);
      } else {
        _this->_impl_.testmsg2_->MergeFrom(*from._impl_.testmsg2_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.testmsg3_ != nullptr);
      if (_this->_impl_.testmsg3_ == nullptr) {
        _this->_impl_.testmsg3_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testmsg3_);
      } else {
        _this->_impl_.testmsg3_->MergeFrom(*from._impl_.testmsg3_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.testheart_ != nullptr);
      if (_this->_impl_.testheart_ == nullptr) {
        _this->_impl_.testheart_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.testheart_);
      } else {
        _this->_impl_.testheart_->MergeFrom(*from._impl_.testheart_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.testd_ = from._impl_.testd_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_testint64() != 0) {
        _this->_impl_.testint64_ = from._impl_.testint64_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_testint32() != 0) {
        _this->_impl_.testint32_ = from._impl_.testint32_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_testsint32() != 0) {
        _this->_impl_.testsint32_ = from._impl_.testsint32_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_testsint64() != 0) {
        _this->_impl_.testsint64_ = from._impl_.testsint64_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (from._internal_testulong() != 0) {
        _this->_impl_.testulong_ = from._impl_.testulong_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (from._internal_testuint() != 0) {
        _this->_impl_.testuint_ = from._impl_.testuint_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (from._internal_testfixed32() != 0) {
        _this->_impl_.testfixed32_ = from._impl_.testfixed32_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (from._internal_testfixed64() != 0) {
        _this->_impl_.testfixed64_ = from._impl_.testfixed64_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (from._internal_testsfixed64() != 0) {
        _this->_impl_.testsfixed64_ = from._impl_.testsfixed64_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x003f0000U)) {
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      if (from._internal_testsfixed32() != 0) {
        _this->_impl_.testsfixed32_ = from._impl_.testsfixed32_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      if (from._internal_testenum() != 0) {
        _this->_impl_.testenum_ = from._impl_.testenum_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      if (from._internal_testbool() != 0) {
        _this->_impl_.testbool_ = from._impl_.testbool_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      if (from._internal_testbool2123123() != 0) {
        _this->_impl_.testbool2123123_ = from._impl_.testbool2123123_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00100000U)) {
      if (from._internal_testenum2() != 0) {
        _this->_impl_.testenum2_ = from._impl_.testenum2_;
      }
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00200000U)) {
      _this->_impl_.testmap_.MergeFrom(from._impl_.testmap_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TestMsg::CopyFrom(const TestMsg& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GamePlayerTest.TestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsg::InternalSwap(TestMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.listint_.InternalSwap(&other->_impl_.listint_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.teststr_, &other->_impl_.teststr_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.testbytes_, &other->_impl_.testbytes_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testenum2_)
      + sizeof(TestMsg::_impl_.testenum2_)
      - PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.testmsg2_)>(
          reinterpret_cast<char*>(&_impl_.testmsg2_),
          reinterpret_cast<char*>(&other->_impl_.testmsg2_));
  _impl_.testmap_.InternalSwap(&other->_impl_.testmap_);
}

::google::protobuf::Metadata TestMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TestMsg2::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<TestMsg2>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(TestMsg2, _impl_._has_bits_);
};

TestMsg2::TestMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg2_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GamePlayerTest.TestMsg2)
}
TestMsg2::TestMsg2(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsg2& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, TestMsg2_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE TestMsg2::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void TestMsg2::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.testint32_ = {};
}
TestMsg2::~TestMsg2() {
  // @@protoc_insertion_point(destructor:GamePlayerTest.TestMsg2)
  SharedDtor(*this);
}
inline void TestMsg2::SharedDtor(MessageLite& self) {
  TestMsg2& this_ = static_cast<TestMsg2&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL TestMsg2::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) TestMsg2(arena);
}
constexpr auto TestMsg2::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TestMsg2),
                                            alignof(TestMsg2));
}
constexpr auto TestMsg2::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_TestMsg2_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &TestMsg2::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<TestMsg2>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &TestMsg2::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<TestMsg2>(), &TestMsg2::ByteSizeLong,
              &TestMsg2::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(TestMsg2, _impl_._cached_size_),
          false,
      },
      &TestMsg2::kDescriptorMethods,
      &descriptor_table_test_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull TestMsg2_class_data_ =
        TestMsg2::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
TestMsg2::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&TestMsg2_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(TestMsg2_class_data_.tc_table);
  return TestMsg2_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
TestMsg2::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TestMsg2, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    TestMsg2_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GamePlayerTest::TestMsg2>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 testInt32 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg2, _impl_.testint32_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(TestMsg2, _impl_.testint32_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 testInt32 = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsg2, _impl_.testint32_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void TestMsg2::Clear() {
// @@protoc_insertion_point(message_clear_start:GamePlayerTest.TestMsg2)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.testint32_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL TestMsg2::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const TestMsg2& this_ = static_cast<const TestMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL TestMsg2::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const TestMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:GamePlayerTest.TestMsg2)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 testInt32 = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_testint32() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_testint32(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GamePlayerTest.TestMsg2)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t TestMsg2::ByteSizeLong(const MessageLite& base) {
  const TestMsg2& this_ = static_cast<const TestMsg2&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t TestMsg2::ByteSizeLong() const {
  const TestMsg2& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:GamePlayerTest.TestMsg2)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 testInt32 = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_testint32() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_testint32());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void TestMsg2::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<TestMsg2*>(&to_msg);
  auto& from = static_cast<const TestMsg2&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:GamePlayerTest.TestMsg2)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_testint32() != 0) {
      _this->_impl_.testint32_ = from._impl_.testint32_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void TestMsg2::CopyFrom(const TestMsg2& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:GamePlayerTest.TestMsg2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsg2::InternalSwap(TestMsg2* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.testint32_, other->_impl_.testint32_);
}

::google::protobuf::Metadata TestMsg2::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GamePlayerTest
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_test_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
