// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf C++ Version: 7.34.1

#ifndef test_2eproto_2epb_2eh
#define test_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "test2.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_test_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_test_2eproto;
}  // extern "C"
namespace GamePlayerTest {
enum TestEnum : int;
extern const uint32_t TestEnum_internal_data_[];
enum TestMsg_TestEnum2 : int;
extern const uint32_t TestMsg_TestEnum2_internal_data_[];
class TestMsg;
struct TestMsgDefaultTypeInternal;
extern TestMsgDefaultTypeInternal _TestMsg_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestMsg_class_data_;
class TestMsg2;
struct TestMsg2DefaultTypeInternal;
extern TestMsg2DefaultTypeInternal _TestMsg2_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestMsg2_class_data_;
class TestMsg_TestMapEntry_DoNotUse;
struct TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal;
extern TestMsg_TestMapEntry_DoNotUseDefaultTypeInternal _TestMsg_TestMapEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestMsg_TestMapEntry_DoNotUse_class_data_;
class TestMsg_TestMsg3;
struct TestMsg_TestMsg3DefaultTypeInternal;
extern TestMsg_TestMsg3DefaultTypeInternal _TestMsg_TestMsg3_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull TestMsg_TestMsg3_class_data_;
}  // namespace GamePlayerTest
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::GamePlayerTest::TestEnum_internal_data_>
    internal::EnumTraitsImpl::value<::GamePlayerTest::TestEnum>;
template <>
internal::EnumTraitsT<::GamePlayerTest::TestMsg_TestEnum2_internal_data_>
    internal::EnumTraitsImpl::value<::GamePlayerTest::TestMsg_TestEnum2>;
}  // namespace protobuf
}  // namespace google

namespace GamePlayerTest {
enum TestMsg_TestEnum2 : int {
  TestMsg_TestEnum2_NORMAL = 0,
  TestMsg_TestEnum2_BOSS = 1,
  TestMsg_TestEnum2_TestMsg_TestEnum2_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TestMsg_TestEnum2_TestMsg_TestEnum2_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TestMsg_TestEnum2_internal_data_[];
inline constexpr TestMsg_TestEnum2 TestMsg_TestEnum2_TestEnum2_MIN =
    static_cast<TestMsg_TestEnum2>(0);
inline constexpr TestMsg_TestEnum2 TestMsg_TestEnum2_TestEnum2_MAX =
    static_cast<TestMsg_TestEnum2>(1);
[[nodiscard]] inline bool TestMsg_TestEnum2_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int TestMsg_TestEnum2_TestEnum2_ARRAYSIZE = 1 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
TestMsg_TestEnum2_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(TestMsg_TestEnum2) {
  return TestMsg_TestEnum2_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& TestMsg_TestEnum2_Name(T value) {
  static_assert(::std::is_same<T, TestMsg_TestEnum2>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TestEnum2_Name().");
  return TestMsg_TestEnum2_Name(static_cast<TestMsg_TestEnum2>(value));
}
template <>
[[nodiscard]] inline const ::std::string& TestMsg_TestEnum2_Name(TestMsg_TestEnum2 value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TestMsg_TestEnum2_descriptor, 0, 1>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool TestMsg_TestEnum2_Parse(
    ::absl::string_view name, TestMsg_TestEnum2* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TestMsg_TestEnum2>(TestMsg_TestEnum2_descriptor(), name,
                                           value);
}
enum TestEnum : int {
  NORMAL = 0,
  BOSS = 5,
  TestEnum_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TestEnum_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TestEnum_internal_data_[];
inline constexpr TestEnum TestEnum_MIN =
    static_cast<TestEnum>(0);
inline constexpr TestEnum TestEnum_MAX =
    static_cast<TestEnum>(5);
[[nodiscard]] inline bool TestEnum_IsValid(int value) {
  return 0 <= value && value <= 5 && ((33u >> value) & 1) != 0;
}
inline constexpr int TestEnum_ARRAYSIZE = 5 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
TestEnum_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(TestEnum) {
  return TestEnum_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& TestEnum_Name(T value) {
  static_assert(::std::is_same<T, TestEnum>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TestEnum_Name().");
  return TestEnum_Name(static_cast<TestEnum>(value));
}
template <>
[[nodiscard]] inline const ::std::string& TestEnum_Name(TestEnum value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TestEnum_descriptor, 0, 5>(
      static_cast<int>(value));
}
[[nodiscard]] inline bool TestEnum_Parse(
    ::absl::string_view name, TestEnum* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TestEnum>(TestEnum_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TestMsg2 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GamePlayerTest.TestMsg2) */ {
 public:
  inline TestMsg2() : TestMsg2(nullptr) {}
  ~TestMsg2() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestMsg2* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestMsg2));
  }
#endif

  template <typename = void>
  explicit constexpr TestMsg2(::google::protobuf::internal::ConstantInitialized);

  inline TestMsg2(const TestMsg2& from) : TestMsg2(nullptr, from) {}
  inline TestMsg2(TestMsg2&& from) noexcept
      : TestMsg2(nullptr, ::std::move(from)) {}
  inline TestMsg2& operator=(const TestMsg2& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMsg2& operator=(TestMsg2&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const TestMsg2& default_instance() {
    return *reinterpret_cast<const TestMsg2*>(
        &_TestMsg2_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(TestMsg2& a, TestMsg2& b) { a.Swap(&b); }
  inline void Swap(TestMsg2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMsg2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] TestMsg2* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestMsg2>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMsg2& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMsg2& from) { TestMsg2::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestMsg2* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GamePlayerTest.TestMsg2"; }

  explicit TestMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestMsg2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsg2& from);
  TestMsg2(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestMsg2&& from) noexcept
      : TestMsg2(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestInt32FieldNumber = 1,
  };
  // int32 testInt32 = 1;
  void clear_testint32() ;
  [[nodiscard]] ::int32_t testint32() const;
  void set_testint32(::int32_t value);

  private:
  ::int32_t _internal_testint32() const;
  void _internal_set_testint32(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GamePlayerTest.TestMsg2)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestMsg2& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t testint32_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestMsg2_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TestMsg_TestMsg3 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GamePlayerTest.TestMsg.TestMsg3) */ {
 public:
  inline TestMsg_TestMsg3() : TestMsg_TestMsg3(nullptr) {}
  ~TestMsg_TestMsg3() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestMsg_TestMsg3* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestMsg_TestMsg3));
  }
#endif

  template <typename = void>
  explicit constexpr TestMsg_TestMsg3(::google::protobuf::internal::ConstantInitialized);

  inline TestMsg_TestMsg3(const TestMsg_TestMsg3& from) : TestMsg_TestMsg3(nullptr, from) {}
  inline TestMsg_TestMsg3(TestMsg_TestMsg3&& from) noexcept
      : TestMsg_TestMsg3(nullptr, ::std::move(from)) {}
  inline TestMsg_TestMsg3& operator=(const TestMsg_TestMsg3& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMsg_TestMsg3& operator=(TestMsg_TestMsg3&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const TestMsg_TestMsg3& default_instance() {
    return *reinterpret_cast<const TestMsg_TestMsg3*>(
        &_TestMsg_TestMsg3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TestMsg_TestMsg3& a, TestMsg_TestMsg3& b) { a.Swap(&b); }
  inline void Swap(TestMsg_TestMsg3* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMsg_TestMsg3* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] TestMsg_TestMsg3* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestMsg_TestMsg3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMsg_TestMsg3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMsg_TestMsg3& from) { TestMsg_TestMsg3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestMsg_TestMsg3* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GamePlayerTest.TestMsg.TestMsg3"; }

  explicit TestMsg_TestMsg3(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestMsg_TestMsg3(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsg_TestMsg3& from);
  TestMsg_TestMsg3(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestMsg_TestMsg3&& from) noexcept
      : TestMsg_TestMsg3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestInt32FieldNumber = 1,
  };
  // int32 testInt32 = 1;
  void clear_testint32() ;
  [[nodiscard]] ::int32_t testint32() const;
  void set_testint32(::int32_t value);

  private:
  ::int32_t _internal_testint32() const;
  void _internal_set_testint32(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GamePlayerTest.TestMsg.TestMsg3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestMsg_TestMsg3& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t testint32_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestMsg_TestMsg3_class_data_;
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TestMsg_TestMapEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::int32_t, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::int32_t, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  TestMsg_TestMapEntry_DoNotUse();
  template <typename = void>
  explicit constexpr TestMsg_TestMapEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit TestMsg_TestMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_TestMsg_TestMapEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_test_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 49,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull TestMsg_TestMapEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED TestMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GamePlayerTest.TestMsg) */ {
 public:
  inline TestMsg() : TestMsg(nullptr) {}
  ~TestMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TestMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TestMsg));
  }
#endif

  template <typename = void>
  explicit constexpr TestMsg(::google::protobuf::internal::ConstantInitialized);

  inline TestMsg(const TestMsg& from) : TestMsg(nullptr, from) {}
  inline TestMsg(TestMsg&& from) noexcept
      : TestMsg(nullptr, ::std::move(from)) {}
  inline TestMsg& operator=(const TestMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMsg& operator=(TestMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const TestMsg& default_instance() {
    return *reinterpret_cast<const TestMsg*>(
        &_TestMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TestMsg& a, TestMsg& b) { a.Swap(&b); }
  inline void Swap(TestMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] TestMsg* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TestMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TestMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TestMsg& from) { TestMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TestMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "GamePlayerTest.TestMsg"; }

  explicit TestMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  TestMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const TestMsg& from);
  TestMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, TestMsg&& from) noexcept
      : TestMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using TestMsg3 = TestMsg_TestMsg3;
  using TestEnum2 = TestMsg_TestEnum2;
  static constexpr TestEnum2 NORMAL = TestMsg_TestEnum2_NORMAL;
  static constexpr TestEnum2 BOSS = TestMsg_TestEnum2_BOSS;
  [[nodiscard]] static inline bool TestEnum2_IsValid(int value) {
    return TestMsg_TestEnum2_IsValid(value);
  }
  static constexpr TestEnum2 TestEnum2_MIN = TestMsg_TestEnum2_TestEnum2_MIN;
  static constexpr TestEnum2 TestEnum2_MAX = TestMsg_TestEnum2_TestEnum2_MAX;
  static constexpr int TestEnum2_ARRAYSIZE = TestMsg_TestEnum2_TestEnum2_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TestEnum2_descriptor() {
    return TestMsg_TestEnum2_descriptor();
  }
  template <typename T>
  [[nodiscard]] static inline const ::std::string& TestEnum2_Name(T value) {
    return TestMsg_TestEnum2_Name(value);
  }
  [[nodiscard]] static inline bool TestEnum2_Parse(
      ::absl::string_view name, TestEnum2* PROTOBUF_NONNULL value) {
    return TestMsg_TestEnum2_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kListIntFieldNumber = 16,
    kTestStrFieldNumber = 14,
    kTestBytesFieldNumber = 15,
    kTestMsg2FieldNumber = 19,
    kTestMsg3FieldNumber = 20,
    kTestHeartFieldNumber = 24,
    kTestDFieldNumber = 2,
    kTestInt64FieldNumber = 4,
    kTestInt32FieldNumber = 3,
    kTestSInt32FieldNumber = 5,
    kTestSInt64FieldNumber = 6,
    kTestULongFieldNumber = 8,
    kTestUIntFieldNumber = 7,
    kTestFixed32FieldNumber = 9,
    kTestFixed64FieldNumber = 10,
    kTestSFixed64FieldNumber = 12,
    kTestSFixed32FieldNumber = 11,
    kTestEnumFieldNumber = 18,
    kTestBoolFieldNumber = 13,
    kTestBool2123123FieldNumber = 23,
    kTestEnum2FieldNumber = 21,
    kTestMapFieldNumber = 17,
  };
  // repeated int32 listInt = 16;
  [[nodiscard]] int listint_size()
      const;
  private:
  int _internal_listint_size() const;

  public:
  void clear_listint() ;
  [[nodiscard]] ::int32_t listint(int index) const;
  void set_listint(int index, ::int32_t value);
  void add_listint(::int32_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::int32_t>& listint() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_listint();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_listint() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_listint();

  public:
  // string testStr = 14;
  void clear_teststr() ;
  [[nodiscard]] const ::std::string& teststr() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_teststr(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_teststr();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_teststr();
  void set_allocated_teststr(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_teststr() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_teststr(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_teststr();

  public:
  // bytes testBytes = 15;
  void clear_testbytes() ;
  [[nodiscard]] const ::std::string& testbytes() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_testbytes(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_testbytes();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_testbytes();
  void set_allocated_testbytes(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_testbytes() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_testbytes(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_testbytes();

  public:
  // .GamePlayerTest.TestMsg2 testMsg2 = 19;
  [[nodiscard]] bool has_testmsg2()
      const;
  void clear_testmsg2() ;
  [[nodiscard]] const ::GamePlayerTest::TestMsg2& testmsg2() const;
  [[nodiscard]] ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE release_testmsg2();
  ::GamePlayerTest::TestMsg2* PROTOBUF_NONNULL mutable_testmsg2();
  void set_allocated_testmsg2(::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_testmsg2(::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE value);
  ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE unsafe_arena_release_testmsg2();

  private:
  const ::GamePlayerTest::TestMsg2& _internal_testmsg2() const;
  ::GamePlayerTest::TestMsg2* PROTOBUF_NONNULL _internal_mutable_testmsg2();

  public:
  // .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
  [[nodiscard]] bool has_testmsg3()
      const;
  void clear_testmsg3() ;
  [[nodiscard]] const ::GamePlayerTest::TestMsg_TestMsg3& testmsg3() const;
  [[nodiscard]] ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE release_testmsg3();
  ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NONNULL mutable_testmsg3();
  void set_allocated_testmsg3(::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_testmsg3(::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE value);
  ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE unsafe_arena_release_testmsg3();

  private:
  const ::GamePlayerTest::TestMsg_TestMsg3& _internal_testmsg3() const;
  ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NONNULL _internal_mutable_testmsg3();

  public:
  // .GameSystemTest.HeartMsg testHeart = 24;
  [[nodiscard]] bool has_testheart()
      const;
  void clear_testheart() ;
  [[nodiscard]] const ::GameSystemTest::HeartMsg& testheart() const;
  [[nodiscard]] ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE release_testheart();
  ::GameSystemTest::HeartMsg* PROTOBUF_NONNULL mutable_testheart();
  void set_allocated_testheart(::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_testheart(::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE value);
  ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE unsafe_arena_release_testheart();

  private:
  const ::GameSystemTest::HeartMsg& _internal_testheart() const;
  ::GameSystemTest::HeartMsg* PROTOBUF_NONNULL _internal_mutable_testheart();

  public:
  // optional double testD = 2;
  [[nodiscard]] bool has_testd()
      const;
  void clear_testd() ;
  [[nodiscard]] double testd() const;
  void set_testd(double value);

  private:
  double _internal_testd() const;
  void _internal_set_testd(double value);

  public:
  // int64 testInt64 = 4;
  void clear_testint64() ;
  [[nodiscard]] ::int64_t testint64() const;
  void set_testint64(::int64_t value);

  private:
  ::int64_t _internal_testint64() const;
  void _internal_set_testint64(::int64_t value);

  public:
  // int32 testInt32 = 3;
  void clear_testint32() ;
  [[nodiscard]] ::int32_t testint32() const;
  void set_testint32(::int32_t value);

  private:
  ::int32_t _internal_testint32() const;
  void _internal_set_testint32(::int32_t value);

  public:
  // sint32 testSInt32 = 5;
  void clear_testsint32() ;
  [[nodiscard]] ::int32_t testsint32() const;
  void set_testsint32(::int32_t value);

  private:
  ::int32_t _internal_testsint32() const;
  void _internal_set_testsint32(::int32_t value);

  public:
  // sint64 testSInt64 = 6;
  void clear_testsint64() ;
  [[nodiscard]] ::int64_t testsint64() const;
  void set_testsint64(::int64_t value);

  private:
  ::int64_t _internal_testsint64() const;
  void _internal_set_testsint64(::int64_t value);

  public:
  // uint64 testULong = 8;
  void clear_testulong() ;
  [[nodiscard]] ::uint64_t testulong() const;
  void set_testulong(::uint64_t value);

  private:
  ::uint64_t _internal_testulong() const;
  void _internal_set_testulong(::uint64_t value);

  public:
  // uint32 testUInt = 7;
  void clear_testuint() ;
  [[nodiscard]] ::uint32_t testuint() const;
  void set_testuint(::uint32_t value);

  private:
  ::uint32_t _internal_testuint() const;
  void _internal_set_testuint(::uint32_t value);

  public:
  // fixed32 testFixed32 = 9;
  void clear_testfixed32() ;
  [[nodiscard]] ::uint32_t testfixed32() const;
  void set_testfixed32(::uint32_t value);

  private:
  ::uint32_t _internal_testfixed32() const;
  void _internal_set_testfixed32(::uint32_t value);

  public:
  // fixed64 testFixed64 = 10;
  void clear_testfixed64() ;
  [[nodiscard]] ::uint64_t testfixed64() const;
  void set_testfixed64(::uint64_t value);

  private:
  ::uint64_t _internal_testfixed64() const;
  void _internal_set_testfixed64(::uint64_t value);

  public:
  // sfixed64 testSFixed64 = 12;
  void clear_testsfixed64() ;
  [[nodiscard]] ::int64_t testsfixed64() const;
  void set_testsfixed64(::int64_t value);

  private:
  ::int64_t _internal_testsfixed64() const;
  void _internal_set_testsfixed64(::int64_t value);

  public:
  // sfixed32 testSFixed32 = 11;
  void clear_testsfixed32() ;
  [[nodiscard]] ::int32_t testsfixed32() const;
  void set_testsfixed32(::int32_t value);

  private:
  ::int32_t _internal_testsfixed32() const;
  void _internal_set_testsfixed32(::int32_t value);

  public:
  // .GamePlayerTest.TestEnum testEnum = 18;
  void clear_testenum() ;
  [[nodiscard]] ::GamePlayerTest::TestEnum testenum() const;
  void set_testenum(::GamePlayerTest::TestEnum value);

  private:
  ::GamePlayerTest::TestEnum _internal_testenum() const;
  void _internal_set_testenum(::GamePlayerTest::TestEnum value);

  public:
  // bool testBool = 13;
  void clear_testbool() ;
  [[nodiscard]] bool testbool() const;
  void set_testbool(bool value);

  private:
  bool _internal_testbool() const;
  void _internal_set_testbool(bool value);

  public:
  // bool testBool2123123 = 23;
  void clear_testbool2123123() ;
  [[nodiscard]] bool testbool2123123() const;
  void set_testbool2123123(bool value);

  private:
  bool _internal_testbool2123123() const;
  void _internal_set_testbool2123123(bool value);

  public:
  // .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
  void clear_testenum2() ;
  [[nodiscard]] ::GamePlayerTest::TestMsg_TestEnum2 testenum2() const;
  void set_testenum2(::GamePlayerTest::TestMsg_TestEnum2 value);

  private:
  ::GamePlayerTest::TestMsg_TestEnum2 _internal_testenum2() const;
  void _internal_set_testenum2(::GamePlayerTest::TestMsg_TestEnum2 value);

  public:
  // map<int32, string> testMap = 17;
  [[nodiscard]] int testmap_size()
      const;
  private:
  int _internal_testmap_size() const;

  public:
  void clear_testmap() ;
  [[nodiscard]] const ::google::protobuf::Map<::int32_t, ::std::string>& testmap() const;
  [[nodiscard]] ::google::protobuf::Map<::int32_t, ::std::string>* PROTOBUF_NONNULL mutable_testmap();

  private:
  const ::google::protobuf::Map<::int32_t, ::std::string>& _internal_testmap() const;
  ::google::protobuf::Map<::int32_t, ::std::string>* PROTOBUF_NONNULL _internal_mutable_testmap();

  public:
  // @@protoc_insertion_point(class_scope:GamePlayerTest.TestMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 22,
                                   4, 61,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const TestMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> listint_;
    ::google::protobuf::internal::CachedSize _listint_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr teststr_;
    ::google::protobuf::internal::ArenaStringPtr testbytes_;
    ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE testmsg2_;
    ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE testmsg3_;
    ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE testheart_;
    double testd_;
    ::int64_t testint64_;
    ::int32_t testint32_;
    ::int32_t testsint32_;
    ::int64_t testsint64_;
    ::uint64_t testulong_;
    ::uint32_t testuint_;
    ::uint32_t testfixed32_;
    ::uint64_t testfixed64_;
    ::int64_t testsfixed64_;
    ::int32_t testsfixed32_;
    int testenum_;
    bool testbool_;
    bool testbool2123123_;
    int testenum2_;
    ::google::protobuf::internal::MapField<TestMsg_TestMapEntry_DoNotUse, ::int32_t, ::std::string> testmap_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull TestMsg_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TestMsg_TestMsg3

// int32 testInt32 = 1;
inline void TestMsg_TestMsg3::clear_testint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t TestMsg_TestMsg3::testint32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.TestMsg3.testInt32)
  return _internal_testint32();
}
inline void TestMsg_TestMsg3::set_testint32(::int32_t value) {
  _internal_set_testint32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.TestMsg3.testInt32)
}
inline ::int32_t TestMsg_TestMsg3::_internal_testint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testint32_;
}
inline void TestMsg_TestMsg3::_internal_set_testint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = value;
}

// -------------------------------------------------------------------

// TestMsg

// optional double testD = 2;
inline bool TestMsg::has_testd() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void TestMsg::clear_testd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testd_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double TestMsg::testd() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testD)
  return _internal_testd();
}
inline void TestMsg::set_testd(double value) {
  _internal_set_testd(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testD)
}
inline double TestMsg::_internal_testd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testd_;
}
inline void TestMsg::_internal_set_testd(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testd_ = value;
}

// int32 testInt32 = 3;
inline void TestMsg::clear_testint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t TestMsg::testint32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testInt32)
  return _internal_testint32();
}
inline void TestMsg::set_testint32(::int32_t value) {
  _internal_set_testint32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testInt32)
}
inline ::int32_t TestMsg::_internal_testint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testint32_;
}
inline void TestMsg::_internal_set_testint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = value;
}

// int64 testInt64 = 4;
inline void TestMsg::clear_testint64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint64_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int64_t TestMsg::testint64() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testInt64)
  return _internal_testint64();
}
inline void TestMsg::set_testint64(::int64_t value) {
  _internal_set_testint64(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testInt64)
}
inline ::int64_t TestMsg::_internal_testint64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testint64_;
}
inline void TestMsg::_internal_set_testint64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint64_ = value;
}

// sint32 testSInt32 = 5;
inline void TestMsg::clear_testsint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsint32_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::int32_t TestMsg::testsint32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testSInt32)
  return _internal_testsint32();
}
inline void TestMsg::set_testsint32(::int32_t value) {
  _internal_set_testsint32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testSInt32)
}
inline ::int32_t TestMsg::_internal_testsint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testsint32_;
}
inline void TestMsg::_internal_set_testsint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsint32_ = value;
}

// sint64 testSInt64 = 6;
inline void TestMsg::clear_testsint64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsint64_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::int64_t TestMsg::testsint64() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testSInt64)
  return _internal_testsint64();
}
inline void TestMsg::set_testsint64(::int64_t value) {
  _internal_set_testsint64(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testSInt64)
}
inline ::int64_t TestMsg::_internal_testsint64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testsint64_;
}
inline void TestMsg::_internal_set_testsint64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsint64_ = value;
}

// uint32 testUInt = 7;
inline void TestMsg::clear_testuint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testuint_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline ::uint32_t TestMsg::testuint() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testUInt)
  return _internal_testuint();
}
inline void TestMsg::set_testuint(::uint32_t value) {
  _internal_set_testuint(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testUInt)
}
inline ::uint32_t TestMsg::_internal_testuint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testuint_;
}
inline void TestMsg::_internal_set_testuint(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testuint_ = value;
}

// uint64 testULong = 8;
inline void TestMsg::clear_testulong() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testulong_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::uint64_t TestMsg::testulong() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testULong)
  return _internal_testulong();
}
inline void TestMsg::set_testulong(::uint64_t value) {
  _internal_set_testulong(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testULong)
}
inline ::uint64_t TestMsg::_internal_testulong() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testulong_;
}
inline void TestMsg::_internal_set_testulong(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testulong_ = value;
}

// fixed32 testFixed32 = 9;
inline void TestMsg::clear_testfixed32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testfixed32_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline ::uint32_t TestMsg::testfixed32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testFixed32)
  return _internal_testfixed32();
}
inline void TestMsg::set_testfixed32(::uint32_t value) {
  _internal_set_testfixed32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testFixed32)
}
inline ::uint32_t TestMsg::_internal_testfixed32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testfixed32_;
}
inline void TestMsg::_internal_set_testfixed32(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testfixed32_ = value;
}

// fixed64 testFixed64 = 10;
inline void TestMsg::clear_testfixed64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testfixed64_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::uint64_t TestMsg::testfixed64() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testFixed64)
  return _internal_testfixed64();
}
inline void TestMsg::set_testfixed64(::uint64_t value) {
  _internal_set_testfixed64(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testFixed64)
}
inline ::uint64_t TestMsg::_internal_testfixed64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testfixed64_;
}
inline void TestMsg::_internal_set_testfixed64(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testfixed64_ = value;
}

// sfixed32 testSFixed32 = 11;
inline void TestMsg::clear_testsfixed32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsfixed32_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline ::int32_t TestMsg::testsfixed32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testSFixed32)
  return _internal_testsfixed32();
}
inline void TestMsg::set_testsfixed32(::int32_t value) {
  _internal_set_testsfixed32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testSFixed32)
}
inline ::int32_t TestMsg::_internal_testsfixed32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testsfixed32_;
}
inline void TestMsg::_internal_set_testsfixed32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsfixed32_ = value;
}

// sfixed64 testSFixed64 = 12;
inline void TestMsg::clear_testsfixed64() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsfixed64_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline ::int64_t TestMsg::testsfixed64() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testSFixed64)
  return _internal_testsfixed64();
}
inline void TestMsg::set_testsfixed64(::int64_t value) {
  _internal_set_testsfixed64(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testSFixed64)
}
inline ::int64_t TestMsg::_internal_testsfixed64() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testsfixed64_;
}
inline void TestMsg::_internal_set_testsfixed64(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testsfixed64_ = value;
}

// bool testBool = 13;
inline void TestMsg::clear_testbool() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbool_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00040000U);
}
inline bool TestMsg::testbool() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testBool)
  return _internal_testbool();
}
inline void TestMsg::set_testbool(bool value) {
  _internal_set_testbool(value);
  SetHasBit(_impl_._has_bits_[0], 0x00040000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testBool)
}
inline bool TestMsg::_internal_testbool() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testbool_;
}
inline void TestMsg::_internal_set_testbool(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbool_ = value;
}

// string testStr = 14;
inline void TestMsg::clear_teststr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.teststr_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& TestMsg::teststr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testStr)
  return _internal_teststr();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestMsg::set_teststr(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.teststr_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testStr)
}
inline ::std::string* PROTOBUF_NONNULL TestMsg::mutable_teststr()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_teststr();
  // @@protoc_insertion_point(field_mutable:GamePlayerTest.TestMsg.testStr)
  return _s;
}
inline const ::std::string& TestMsg::_internal_teststr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.teststr_.Get();
}
inline void TestMsg::_internal_set_teststr(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.teststr_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TestMsg::_internal_mutable_teststr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.teststr_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TestMsg::release_teststr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GamePlayerTest.TestMsg.testStr)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.teststr_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.teststr_.Set("", GetArena());
  }
  return released;
}
inline void TestMsg::set_allocated_teststr(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.teststr_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.teststr_.IsDefault()) {
    _impl_.teststr_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GamePlayerTest.TestMsg.testStr)
}

// bytes testBytes = 15;
inline void TestMsg::clear_testbytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbytes_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& TestMsg::testbytes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testBytes)
  return _internal_testbytes();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void TestMsg::set_testbytes(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.testbytes_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testBytes)
}
inline ::std::string* PROTOBUF_NONNULL TestMsg::mutable_testbytes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_testbytes();
  // @@protoc_insertion_point(field_mutable:GamePlayerTest.TestMsg.testBytes)
  return _s;
}
inline const ::std::string& TestMsg::_internal_testbytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testbytes_.Get();
}
inline void TestMsg::_internal_set_testbytes(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbytes_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL TestMsg::_internal_mutable_testbytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.testbytes_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE TestMsg::release_testbytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GamePlayerTest.TestMsg.testBytes)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.testbytes_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.testbytes_.Set("", GetArena());
  }
  return released;
}
inline void TestMsg::set_allocated_testbytes(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.testbytes_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.testbytes_.IsDefault()) {
    _impl_.testbytes_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:GamePlayerTest.TestMsg.testBytes)
}

// repeated int32 listInt = 16;
inline int TestMsg::_internal_listint_size() const {
  return _internal_listint().size();
}
inline int TestMsg::listint_size() const {
  return _internal_listint_size();
}
inline void TestMsg::clear_listint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.listint_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t TestMsg::listint(int index) const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.listInt)
  return _internal_listint().Get(index);
}
inline void TestMsg::set_listint(int index, ::int32_t value) {
  _internal_mutable_listint()->Set(index, value);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.listInt)
}
inline void TestMsg::add_listint(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_listint()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:GamePlayerTest.TestMsg.listInt)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& TestMsg::listint() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:GamePlayerTest.TestMsg.listInt)
  return _internal_listint();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL TestMsg::mutable_listint()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:GamePlayerTest.TestMsg.listInt)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_listint();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
TestMsg::_internal_listint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.listint_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
TestMsg::_internal_mutable_listint() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.listint_;
}

// map<int32, string> testMap = 17;
inline int TestMsg::_internal_testmap_size() const {
  return _internal_testmap().size();
}
inline int TestMsg::testmap_size() const {
  return _internal_testmap_size();
}
inline void TestMsg::clear_testmap() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testmap_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00200000U);
}
inline const ::google::protobuf::Map<::int32_t, ::std::string>& TestMsg::_internal_testmap() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testmap_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::std::string>& TestMsg::testmap() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:GamePlayerTest.TestMsg.testMap)
  return _internal_testmap();
}
inline ::google::protobuf::Map<::int32_t, ::std::string>* PROTOBUF_NONNULL TestMsg::_internal_mutable_testmap() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.testmap_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::std::string>* PROTOBUF_NONNULL TestMsg::mutable_testmap()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00200000U);
  // @@protoc_insertion_point(field_mutable_map:GamePlayerTest.TestMsg.testMap)
  return _internal_mutable_testmap();
}

// .GamePlayerTest.TestEnum testEnum = 18;
inline void TestMsg::clear_testenum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testenum_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00020000U);
}
inline ::GamePlayerTest::TestEnum TestMsg::testenum() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testEnum)
  return _internal_testenum();
}
inline void TestMsg::set_testenum(::GamePlayerTest::TestEnum value) {
  _internal_set_testenum(value);
  SetHasBit(_impl_._has_bits_[0], 0x00020000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testEnum)
}
inline ::GamePlayerTest::TestEnum TestMsg::_internal_testenum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GamePlayerTest::TestEnum>(_impl_.testenum_);
}
inline void TestMsg::_internal_set_testenum(::GamePlayerTest::TestEnum value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testenum_ = value;
}

// .GamePlayerTest.TestMsg2 testMsg2 = 19;
inline bool TestMsg::has_testmsg2() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.testmsg2_ != nullptr);
  return value;
}
inline void TestMsg::clear_testmsg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testmsg2_ != nullptr) _impl_.testmsg2_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::GamePlayerTest::TestMsg2& TestMsg::_internal_testmsg2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GamePlayerTest::TestMsg2* p = _impl_.testmsg2_;
  return p != nullptr ? *p : reinterpret_cast<const ::GamePlayerTest::TestMsg2&>(::GamePlayerTest::_TestMsg2_default_instance_);
}
inline const ::GamePlayerTest::TestMsg2& TestMsg::testmsg2() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testMsg2)
  return _internal_testmsg2();
}
inline void TestMsg::unsafe_arena_set_allocated_testmsg2(
    ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testmsg2_);
  }
  _impl_.testmsg2_ = reinterpret_cast<::GamePlayerTest::TestMsg2*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GamePlayerTest.TestMsg.testMsg2)
}
inline ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE TestMsg::release_testmsg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::GamePlayerTest::TestMsg2* released = _impl_.testmsg2_;
  _impl_.testmsg2_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE TestMsg::unsafe_arena_release_testmsg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GamePlayerTest.TestMsg.testMsg2)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::GamePlayerTest::TestMsg2* temp = _impl_.testmsg2_;
  _impl_.testmsg2_ = nullptr;
  return temp;
}
inline ::GamePlayerTest::TestMsg2* PROTOBUF_NONNULL TestMsg::_internal_mutable_testmsg2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testmsg2_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GamePlayerTest::TestMsg2>(GetArena());
    _impl_.testmsg2_ = reinterpret_cast<::GamePlayerTest::TestMsg2*>(p);
  }
  return _impl_.testmsg2_;
}
inline ::GamePlayerTest::TestMsg2* PROTOBUF_NONNULL TestMsg::mutable_testmsg2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::GamePlayerTest::TestMsg2* _msg = _internal_mutable_testmsg2();
  // @@protoc_insertion_point(field_mutable:GamePlayerTest.TestMsg.testMsg2)
  return _msg;
}
inline void TestMsg::set_allocated_testmsg2(::GamePlayerTest::TestMsg2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testmsg2_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.testmsg2_ = reinterpret_cast<::GamePlayerTest::TestMsg2*>(value);
  // @@protoc_insertion_point(field_set_allocated:GamePlayerTest.TestMsg.testMsg2)
}

// .GamePlayerTest.TestMsg.TestMsg3 testMsg3 = 20;
inline bool TestMsg::has_testmsg3() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.testmsg3_ != nullptr);
  return value;
}
inline void TestMsg::clear_testmsg3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testmsg3_ != nullptr) _impl_.testmsg3_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::GamePlayerTest::TestMsg_TestMsg3& TestMsg::_internal_testmsg3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GamePlayerTest::TestMsg_TestMsg3* p = _impl_.testmsg3_;
  return p != nullptr ? *p : reinterpret_cast<const ::GamePlayerTest::TestMsg_TestMsg3&>(::GamePlayerTest::_TestMsg_TestMsg3_default_instance_);
}
inline const ::GamePlayerTest::TestMsg_TestMsg3& TestMsg::testmsg3() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testMsg3)
  return _internal_testmsg3();
}
inline void TestMsg::unsafe_arena_set_allocated_testmsg3(
    ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testmsg3_);
  }
  _impl_.testmsg3_ = reinterpret_cast<::GamePlayerTest::TestMsg_TestMsg3*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GamePlayerTest.TestMsg.testMsg3)
}
inline ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE TestMsg::release_testmsg3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::GamePlayerTest::TestMsg_TestMsg3* released = _impl_.testmsg3_;
  _impl_.testmsg3_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE TestMsg::unsafe_arena_release_testmsg3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GamePlayerTest.TestMsg.testMsg3)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::GamePlayerTest::TestMsg_TestMsg3* temp = _impl_.testmsg3_;
  _impl_.testmsg3_ = nullptr;
  return temp;
}
inline ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NONNULL TestMsg::_internal_mutable_testmsg3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testmsg3_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GamePlayerTest::TestMsg_TestMsg3>(GetArena());
    _impl_.testmsg3_ = reinterpret_cast<::GamePlayerTest::TestMsg_TestMsg3*>(p);
  }
  return _impl_.testmsg3_;
}
inline ::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NONNULL TestMsg::mutable_testmsg3()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::GamePlayerTest::TestMsg_TestMsg3* _msg = _internal_mutable_testmsg3();
  // @@protoc_insertion_point(field_mutable:GamePlayerTest.TestMsg.testMsg3)
  return _msg;
}
inline void TestMsg::set_allocated_testmsg3(::GamePlayerTest::TestMsg_TestMsg3* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testmsg3_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.testmsg3_ = reinterpret_cast<::GamePlayerTest::TestMsg_TestMsg3*>(value);
  // @@protoc_insertion_point(field_set_allocated:GamePlayerTest.TestMsg.testMsg3)
}

// .GamePlayerTest.TestMsg.TestEnum2 testEnum2 = 21;
inline void TestMsg::clear_testenum2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testenum2_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00100000U);
}
inline ::GamePlayerTest::TestMsg_TestEnum2 TestMsg::testenum2() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testEnum2)
  return _internal_testenum2();
}
inline void TestMsg::set_testenum2(::GamePlayerTest::TestMsg_TestEnum2 value) {
  _internal_set_testenum2(value);
  SetHasBit(_impl_._has_bits_[0], 0x00100000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testEnum2)
}
inline ::GamePlayerTest::TestMsg_TestEnum2 TestMsg::_internal_testenum2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::GamePlayerTest::TestMsg_TestEnum2>(_impl_.testenum2_);
}
inline void TestMsg::_internal_set_testenum2(::GamePlayerTest::TestMsg_TestEnum2 value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testenum2_ = value;
}

// bool testBool2123123 = 23;
inline void TestMsg::clear_testbool2123123() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbool2123123_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00080000U);
}
inline bool TestMsg::testbool2123123() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testBool2123123)
  return _internal_testbool2123123();
}
inline void TestMsg::set_testbool2123123(bool value) {
  _internal_set_testbool2123123(value);
  SetHasBit(_impl_._has_bits_[0], 0x00080000U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg.testBool2123123)
}
inline bool TestMsg::_internal_testbool2123123() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testbool2123123_;
}
inline void TestMsg::_internal_set_testbool2123123(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testbool2123123_ = value;
}

// .GameSystemTest.HeartMsg testHeart = 24;
inline bool TestMsg::has_testheart() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  PROTOBUF_ASSUME(!value || _impl_.testheart_ != nullptr);
  return value;
}
inline const ::GameSystemTest::HeartMsg& TestMsg::_internal_testheart() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::GameSystemTest::HeartMsg* p = _impl_.testheart_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameSystemTest::HeartMsg&>(::GameSystemTest::_HeartMsg_default_instance_);
}
inline const ::GameSystemTest::HeartMsg& TestMsg::testheart() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg.testHeart)
  return _internal_testheart();
}
inline void TestMsg::unsafe_arena_set_allocated_testheart(
    ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testheart_);
  }
  _impl_.testheart_ = reinterpret_cast<::GameSystemTest::HeartMsg*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GamePlayerTest.TestMsg.testHeart)
}
inline ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE TestMsg::release_testheart() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::GameSystemTest::HeartMsg* released = _impl_.testheart_;
  _impl_.testheart_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE TestMsg::unsafe_arena_release_testheart() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:GamePlayerTest.TestMsg.testHeart)

  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::GameSystemTest::HeartMsg* temp = _impl_.testheart_;
  _impl_.testheart_ = nullptr;
  return temp;
}
inline ::GameSystemTest::HeartMsg* PROTOBUF_NONNULL TestMsg::_internal_mutable_testheart() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.testheart_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::GameSystemTest::HeartMsg>(GetArena());
    _impl_.testheart_ = reinterpret_cast<::GameSystemTest::HeartMsg*>(p);
  }
  return _impl_.testheart_;
}
inline ::GameSystemTest::HeartMsg* PROTOBUF_NONNULL TestMsg::mutable_testheart()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::GameSystemTest::HeartMsg* _msg = _internal_mutable_testheart();
  // @@protoc_insertion_point(field_mutable:GamePlayerTest.TestMsg.testHeart)
  return _msg;
}
inline void TestMsg::set_allocated_testheart(::GameSystemTest::HeartMsg* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.testheart_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }

  _impl_.testheart_ = reinterpret_cast<::GameSystemTest::HeartMsg*>(value);
  // @@protoc_insertion_point(field_set_allocated:GamePlayerTest.TestMsg.testHeart)
}

// -------------------------------------------------------------------

// TestMsg2

// int32 testInt32 = 1;
inline void TestMsg2::clear_testint32() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t TestMsg2::testint32() const {
  // @@protoc_insertion_point(field_get:GamePlayerTest.TestMsg2.testInt32)
  return _internal_testint32();
}
inline void TestMsg2::set_testint32(::int32_t value) {
  _internal_set_testint32(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:GamePlayerTest.TestMsg2.testInt32)
}
inline ::int32_t TestMsg2::_internal_testint32() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.testint32_;
}
inline void TestMsg2::_internal_set_testint32(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.testint32_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GamePlayerTest


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::GamePlayerTest::TestMsg_TestEnum2> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GamePlayerTest::TestMsg_TestEnum2>() {
  return ::GamePlayerTest::TestMsg_TestEnum2_descriptor();
}
template <>
struct is_proto_enum<::GamePlayerTest::TestEnum> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::GamePlayerTest::TestEnum>() {
  return ::GamePlayerTest::TestEnum_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // test_2eproto_2epb_2eh
